### PR TITLE
Updates-06042020

### PR DESCRIPTION
**Pull request by AaronMountford**
Fixes for latest HASS

### CODE REVIEW

**Comment by maartenpaauw** [comment]
Nice, I see you managed to create a PR! Good job. The code is checked by a linter so it stays clean. Do you think you will be able to fix these errors? Let me know if you need some help.

**Comment by AaronMountford** [comment]
Hi Maarten.    

Fully appreciate the use of the linter (have used them myself for other projects), however I have to take exception with the key ordering rule - If I were to re-order the code it would take ages, and remove readability and sense.  Is it possible to have this disabled?

Can you let me know what the number of spaces before comments setting is set to?  I can easily fix this I guess, but 99% of the comments do have one space after the # already which seems pretty standard for yaml.

`  25:28     error    too few spaces before comment  (comments)
  26:3      error    wrong ordering of key "accent-color" in mapping  (key-ordering)`

**Comment by maartenpaauw** [comment]
Good point, you can disable the key ordering rule by deleting the following lines: https://github.com/home-assistant-community-themes/solarized-light/blob/master/.yamllint#L59-L60

About the spaces before a comment I'm not sure. I think it should be 2. https://yamllint.readthedocs.io/en/stable/rules.html#module-yamllint.rules.comments

**Comment by maartenpaauw** [comment]
Do you think you will work this out or do you need some help?

**Comment by maartenpaauw** [comment]
I'm gonna close this pull request because of 1 year inactivity.

**Pull request closed without merging**
